[package]
name = "stayreal"
version = "0.7.0"
description = "An open-source, lightweight and privacy-focused alternative client for a popular authentic social network."
authors = ["Mikkel ALMONTE--RINGAUD <contact@vexcited.com>"]
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "stayreal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["webview-data-url"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = "2"
tauri-plugin-os = "2"
tauri-plugin-internal-api = { path = "../internal-api" }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }

[package.metadata.patch]
crates = ["wry"]

[patch.crates-io]
wry = { path = "./target/patch/wry-0.52.1" }
